### ISSUE TITLE
LMP插件问题：ModuleNotFoundError: No module named 'settings'

### ISSUE THREAD

**Issue by byxzone** [linuxkerneltravel/lmp#213]
Traceback (most recent call last):
  File "./plugins/oomkill.py", line 24, in <module>
    from db_modules import write2db
  File "/home/ubuntu/lmp2/plugins/db_modules.py", line 7, in <module>
    from db_writer.writerImpl import writer_factory
  File "/home/ubuntu/lmp2/plugins/db_writer/writerImpl.py", line 11, in <module>
    from settings.const import DatabaseType
ModuleNotFoundError: No module named 'settings'

**Comment by helight** [comment]
不要关，问题还没有解决

**Comment by Teanix** [comment]
已经解决
