### ISSUE TITLE
ubuntu运行lmp“'generated/autoconf.h' file not found”

### ISSUE THREAD

**Issue by FoxVolant** [linuxkerneltravel/lmp#219]
环境描述：
ubuntu 5.11.0-40

bug描述：
In file included from <built-in>:1:
././include/linux/kconfig.h:7:10: fatal error: 'generated/autoconf.h' file not found
#include <generated/autoconf.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "./plugins/vfsstat.py", line 36, in <module>
    b = BPF(text="""
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
In file included from <built-in>:1:

因为bug描述为缺少generated/autoconf.h，将同一个版本的ubuntu的generated/autoconf.h找来加到后面，出现新的bug：
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:51:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1

**Comment by FoxVolant** [comment]
在ubuntu5.4版本上能跑通，感觉可能是ubuntu5.11本身的原因
